### ISSUE TITLE
pub get return errors, pub get failed

### ISSUE THREAD

**Issue by terrasuscompany** [britannio/in_app_review#24] opened 2021-03-10 13:49 UTC
There is some conflict i think. 

Because in_app_review >=2.0.1 depends on in_app_review_platform_interface ^2.0.2 which depends on url_launcher ^6.0.0, in_app_review >=2.0.1 requires url_launcher ^6.0.0.
And because youtube_player_iframe 1.2.0+2 depends on url_launcher ^5.7.10 and no versions of youtube_player_iframe match >1.2.0+2 <2.0.0, in_app_review >=2.0.1 is incompatible with youtube_player_iframe ^1.2.0+2.

**Comment by terrasuscompany** [comment] 2021-03-10 13:58
Thus, in_app_review >=2.0.1 is incompatible with firebase_analytics ^6.2.0.

**Comment by britannio** [comment] 2021-03-10 14:12
Seems like this is the problem: https://github.com/sarbagyastha/youtube_player_flutter/issues/456
Also, version 7.1.0 of firebase_analytics should be compatible with the latest version of this plugin.

**Comment by britannio** [comment] 2021-03-10 14:13
A temporary fix may be adding the following to pubspec.yaml:
```yaml
dependency_overrides:
    url_launcher: ^6.0.0
```

**Comment by britannio** [comment] 2021-03-24 06:53
Closing as this issue is caused by a separate package

**Closed by britannio** 2021-03-24 06:53 UTC
