### ISSUE TITLE
Is is possible add "only show the app store page" (not review)

### ISSUE THREAD

**Issue by dodatw** [britannio/in_app_review#22] opened 2021-02-25 05:36 UTC
This is a very useful tool.
Is it possible to add parameters that can go to the app store page?
Just like `writeReview` in https://github.com/Purus/launch_review#ios-specifics

If it is, I don't need to add two libraries.

Doda

**Comment by britannio** [comment] 2021-02-25 09:12
Like https://github.com/britannio/in_app_review#openstorelisting but without requesting a review?

**Comment by dodatw** [comment] 2021-02-25 10:28
YES!

**Comment by dodatw** [comment] 2021-02-25 10:31
One more request, 
Can we set androidAppId ?
That's mean openstorelisting  not only can go to this app store page. it also can go to other app store page.

**Comment by britannio** [comment] 2021-02-25 10:32
Have you tried it out? Is there any reason why you want to open the store listing but without also presenting a popup within the IOS App Store?

**Comment by dodatw** [comment] 2021-02-25 10:39
We want to show some information let user know in store page.

**Comment by NickanBagherpour** [comment] 2021-03-24 19:42
Hi
store_redirect package has method like 
`StoreRedirect.redirect(androidAppId: "com.x.y", iOSAppId: "585027354");`
that redirect user to  user's app in store like GooglePlay, etc ...
this is very useful for updating and showing some info

btw: sorry for my English

**Comment by rocboronat** [comment] 2021-04-19 11:50
@NickanBagherpour just for the info, in case you didn't try it. On Android, `openStoreListing` shows the app page on Google Play. It doesn't need the package name because it's just the package name. You would need to have that parameter only if you want to open another app's page, which is not usual.

**Comment by edocabhi** [comment] 2021-08-25 10:44
One way to achieve this with the current implementation would be as follows.

```dart
if (Platform.isIOS) {
  launch("https://apps.apple.com/app/1010101010"); //replace with your app_Id
} else if (Platform.isAndroid) {
  InAppReview _inAppReview = InAppReview.instance;
  if (await _inAppReview.isAvailable()) {
    _inAppReview.openStoreListing();
  }
}
```

Here ```launch()``` method is used to launch any URL using [url_launcher](https://pub.dev/packages/url_launcher)

**Comment by britannio** [comment] 2021-08-25 10:54
@edocabhi You only need to use `isAvailable()` before `requestReview()`.

**Comment by edocabhi** [comment] 2021-08-25 10:56
@britannio Thanks for the suggestion. Updated snippet.

**Comment by derDeno** [comment] 2022-10-28 02:08
Had the same problem and added it in a fork. See this response here

https://github.com/britannio/in_app_review/issues/53#issuecomment-1294345897

**Comment by britannio** [comment] 2022-11-26 16:28
Closing as a duplicate of https://github.com/britannio/in_app_review/issues/22

**Closed by britannio** 2022-11-26 16:28 UTC
